In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [20]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorization Version: " + str(1000*(toc-tic)) + " ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("For Loop Version: " + str(1000*(toc-tic)) + " ms")

Vectorization Version: 0.9870529174804688 ms
For Loop Version: 526.5719890594482 ms


In [21]:
tic = time.time()
d = np.exp(a)
toc = time.time()
print("Vectorization Version: " + str(1000*(toc-tic)) + " ms")

import math
c = 0
tic = time.time()
for i in range(1000000):
    d[i] = math.exp(a[i])
toc = time.time()
print("For Loop Version: " + str(1000*(toc-tic)) + " ms")

Vectorization Version: 58.83979797363281 ms
For Loop Version: 351.0608673095703 ms


In [22]:
# Broadcasting
A = np.array([[56.0, 6.0, 4.4, 68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
s = np.sum(A,axis=0)
percentage = 100*A/s
print(percentage)

[[94.91525424  2.44897959  2.83140283 88.42652796]
 [ 2.03389831 42.44897959 33.46203346 10.40312094]
 [ 3.05084746 55.10204082 63.70656371  1.17035111]]
